language: go

go:
#  - 1.8.x
  - 1.9.x

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo

script:
 #- ginkgo -r --cover --trace --race
 - go test ./... -cover
 
 notifications:
    slack: ciintegration:AC6xEir9MAtxFTkOmcJs38Gm