language: go

go:
#  - 1.8.x add aditional versions to execute a matrix job
  - 1.9.x

install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/alecthomas/gometalinter

before_script:
  - gometalinter --install --update

script:
  #- ginkgo -r --cover --trace --race

  # Execute static checks
  - echo "Static checks execution"
  - gometalinter  ./...
  - echo "End static checks"

  #Execute tests
  - echo "Test execution"
  - go test ./... -cover
  - echo "End test execution"
  
notifications:
  slack: ciintegration:AC6xEir9MAtxFTkOmcJs38Gm